### ISSUE TITLE
EPIC: Interchain should have Sane Defaults for public project mgmt ("Backlog Interop")

### ISSUE THREAD

**Issue by jonathanpberger** [interchainio/interchain_public_works#1]
```[tasklist]
### Tasks
- [x] get Ollie to create public `interchain/interchain_public_works` repo https://github.com/interchainio/interchain_public_works
- [ ] move this ticket to IPW and add Nico and Ollie
- [ ] create `interchainio/interchain_public_works` gh **project**
- [ ] create Backlog Interop Wiki
- [ ] create Interchain PHEELblog (and a few Hello World posts). GH Pages?
- [ ] ⚡️ articulate what "backlog interop" means (blog post?): story types, statuses, board automation, etc
- [ ] make projects (see list below) Backlog-Interop compliant
- [ ] do more work on Cosmos-SDK
- [ ] socialize it (PHEELblog)
- [ ] put out a call to ToT: who's in next?
```

```[tasklist]
### Projects to onboard to Backlog Interop
- [ ] Cosmos-SDK
- [ ] IBC-wasm
- [ ] cosmos/IBC-apps
- [ ] strangelove-ventures/horcrux
- [ ] strangelove-ventures/interchaintest, 
- [ ] abstract.money
- [ ] some informal?
- [ ] some IG?
- [ ] some other ToT?
```
